[build]
command = "npm run build"
publish = "dist"
functions = "netlify/functions"

[[redirects]]
from = "/*"
to = "/index.html"
status = 200

#[[redirects]]
#from = "/api/proxy"
#to = "/.netlify/functions/proxy"
#status = 200
#force = true

[[redirects]]
from = "/api/*"
to = "https://ets.lhsr.sh.gov.cn/:splat"
status = 200
force = true

[[headers]]
for = "/api/*"
[headers.values]
  Access-Control-Allow-Origin = "*"
  Access-Control-Allow-Methods = "GET, POST, PUT, DELETE, OPTIONS"
  Access-Control-Allow-Headers = "Content-Type, Authorization"

