[build]
command = "npm run build"
publish = "dist"
#functions = "netlify/functions"
#
#[[redirects]]
#from = "/proxy/"
#to = "/.netlify/functions/proxy:splat"
#status = 200
#force = true

#[[redirects]]
#from = "/*"
#to = "/index.html"
#status = 200

# https://upload-image-sh.netlify.app/shanhe/api/za/chouq.php
# http://shanhe.kim/api/za/chouq.php
[[redirects]]
from = "/shanhe/*"
to = "http://shanhe.kim/:splat"
status = 200
force = true

#[[redirects]]
#from = "/api/*"
#to = "https://ets.lhsr.sh.gov.cn/:splat"
#status = 200
#force = true
#
#[[headers]]
#for = "/api/*"
#[headers.values]
#  Access-Control-Allow-Origin = "*"
#  Access-Control-Allow-Methods = "GET, POST, PUT, DELETE, OPTIONS"
#  Access-Control-Allow-Headers = "Content-Type, Authorization"

