[build]
  command = "npm run build"
  publish = "dist"

[[redirects]]
from = "/*"
to = "/index.html"
status = 200

[[redirects]]
from = "/api/*"
to = "https://api.example.com/:splat"
status = 200
force = true

[[redirects]]
from = "/shcws/*"
to = "https://ets.lhsr.sh.gov.cn/shcws/:splat"
status = 200
force = true
